name: DuckSuiteSpawns
main : org.cyberiantiger.minecraft.ducksuite.spawn.DuckSuiteSpawns
version: ${project.version}b-${project.build.number}
description: Part of the DuckSuite this plugin allows users to set a proxy wide spawn
author: geNAZt, CyberTiger
depend: [DuckSuiteTeleports]
commands:
    setnewspawn:
        description: Sets the new players spawn point.
        permission: ducksuite.spawns.command.setnewspawn
        aliases: [sns, setnewplayerspawn, setnoobspawn]
        permission-message: §cYou do not have permission for this command
    setworldspawn:
        description: Sets the proxies world spawn point.
        permission: ducksuite.spawns.command.setworldspawn
        aliases: [sws]
        permission-message: §cYou do not have permission for this command
    setserverspawn:
        description: Sets the servers spawn point.
        permission: ducksuite.spawns.command.setserverspawn
        aliases: [sss]
        permission-message: §cYou do not have permission for this command
    setglobalspawn:
        description: Sets the proxies global spawn point.
        permission: ducksuite.spawns.command.setglobalspawn
        aliases: [sgs, setproxyspawn,sethub,sethubspawn]
        permission-message: §cYou do not have permission for this command
    spawn:
        description: Sends the player to the relevent spawn
        permission: ducksuite.spawns.command.spawn
        permission-message: §cYou do not have permission for this command
    worldspawn:
        description: Sends the player to the worlds spawn
        permission: ducksuite.spawns.command.worldspawn
        aliases: [ws]
        permission-message: §cYou do not have permission for this command
    serverspawn:
        description: Sends the player to the servers spawn
        permission: ducksuite.spawns.command.serverspawn
        aliases: [ss]
        permission-message: §cYou do not have permission for this command
    globalspawn:
        description: Sends the player to the proxys spawn
        permission: ducksuite.spawns.command.globalspawn
        aliases: [gs,hub,lobby]
        permission-message: §cYou do not have permission for this command

permissions:
    ducksuite.spawns.*:
        description: gives access to all DuckSuiteSpawns commands and features
        default: op
        children:
            ducksuite.spawns.admin: true
    ducksuite.spawns.admin:
        description: gives access to all admin features of DuckSuiteSpawns
        children:
            ducksuite.spawns.command.setnewspawn: true
            ducksuite.spawns.command.setworldspawn: true
            ducksuite.spawns.command.setserverspawn: true
            ducksuite.spawns.command.setglobalspawn: true
            ducksuite.spawns.command.spawn: true
            ducksuite.spawns.command.worldspawn: true
            ducksuite.spawns.command.serverspawn: true
            ducksuite.spawns.command.globalspawn: true
    ducksuite.spawns.new.world:
        description: Teleports players with no server.data to the world spawn on first connect
        default: false
    ducksuite.spawns.new.server:
        description: Teleports players with no server.data to the server spawn on first connect
        default: false
    ducksuite.spawns.new.global:
        description: Teleports players with no server.data to the proxy spawn on first connect
        default: false
    ducksuite.spawns.spawn.bed:
        description: If a player has a bed spawn then the player will respawn at the bed on death
        default: false
    ducksuite.spawns.spawn.world:
        description: IF the player doesnt have a bed location or bed perm then the player will respawn at the world spawn if there is one
        default: false
    ducksuite.spawns.spawn.server:
        description: If the player doesnt have the world/bed perms or there is no bed/world spawn location the player will spawn at the server spawn if there is one on death
        default: false
    ducksuite.spawns.spawn.global:
        description: On death if none of the previous cases are met the player will respawn at the proxy spawn.
        default: false
    
